# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Word.create(created_by: 1, foreign_word: 'ombrello', english_word: 'umbrella', part_of_speech: 'noun', category: 'weather', language: 'Italian', sound_present: false)
Word.create(created_by: 1, foreign_word: 'topo', english_word: 'mouse', part_of_speech: 'noun', category: 'animals', language: 'Italian', sound_present: false)
Word.create(created_by: 1, foreign_word: 'cane', english_word: 'dog', part_of_speech: 'noun', category: 'animals', language: 'Italian', sound_present: false)
Word.create(created_by: 1, foreign_word: 'balena', english_word: 'whale', part_of_speech: 'noun', category: 'animals', language: 'Italian', sound_present: false)


Word.create(english_word: 'knife', foreign_word: 'hnífur', part_of_speech: 'noun', category: 'kitchen', language: 'Icelandic', sound_present: false)
Word.create(english_word: 'fork', foreign_word: 'gafall', part_of_speech: 'noun', category: 'kitchen', language: 'Icelandic', sound_present: false)
Word.create(english_word: 'spoon', foreign_word: 'skeið', part_of_speech: 'noun', category: 'kitchen', language: 'Icelandic', sound_present: false)
Word.create(english_word: 'plate', foreign_word: 'diskur', part_of_speech: 'noun', category: 'kitchen', language: 'Icelandic', sound_present: false)
Word.create(english_word: 'that', foreign_word: 'það', part_of_speech: 'pronoun', language: 'Icelandic', sound_present: false)
Word.create(english_word: 'not', foreign_word: 'ekki', part_of_speech: 'adverb', language: 'Icelandic', sound_present: false)
Word.create(english_word: 'to eat', foreign_word: 'að borða', part_of_speech: 'verb', category: 'kitchen', language: 'Icelandic', sound_present: false)
Word.create(english_word: 'to cook', foreign_word: 'að elda', part_of_speech: 'verb', category: 'kitchen', language: 'Icelandic', sound_present: false)
Word.create(english_word: 'snow', foreign_word: 'snjór', part_of_speech: 'noun', category: 'weather', language: 'Icelandic', sound_present: false)
Word.create(english_word: 'to snow', foreign_word: 'að snjóa', part_of_speech: 'verb', category: 'weather', language: 'Icelandic', sound_present: false)


Language.create(language: 'Spanish')
Language.create(language: 'French')
Language.create(language: 'Deutsch')
Language.create(language: 'Italian')
Language.create(language: 'Greek')
Language.create(language: 'Hungarian')
Language.create(language: 'Turkish')
Language.create(language: 'Russian')
Language.create(language: 'Dutch')
Language.create(language: 'Swedish')
Language.create(language: 'Norwegian')
Language.create(language: 'Japanese')
Language.create(language: 'Korean')
Language.create(language: 'Chinese')
Language.create(language: 'Hindi')
Language.create(language: 'Serbian')
Language.create(language: 'Croatian')
Language.create(language: 'Bosnian')
Language.create(language: 'Romanian')
Language.create(language: 'Catalan')
Language.create(language: 'Australian')
Language.create(language: 'Finnish')
Language.create(language: 'Afrikaans')
Language.create(language: 'Albanian')
Language.create(language: 'Arabic')
Language.create(language: 'Armenian')
Language.create(language: 'Czech')
Language.create(language: 'Danish')
Language.create(language: 'Esperanto')
Language.create(language: 'Creole')
Language.create(language: 'Icelandic')
Language.create(language: 'Indonesian')
Language.create(language: 'Latin')
Language.create(language: 'Latvian')
Language.create(language: 'Macedonian')
Language.create(language: 'Moldavian')
Language.create(language: 'Montenegrin')
Language.create(language: 'Polish')
Language.create(language: 'Portuguese')
Language.create(language: 'Serbo-Croatian')
Language.create(language: 'Slovak')
Language.create(language: 'Spanish')
Language.create(language: 'Swahili')
Language.create(language: 'Tamil')
Language.create(language: 'Thai')
Language.create(language: 'Vietnamese')
Language.create(language: 'Welsh')
